from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
from reportlab.lib.units import inch
import logging
from datetime import datetime
from config import REPORTS_DIR

logger = logging.getLogger(__name__)

class ReportGenerator:
    """Generate PDF and CSV reports"""
    
    def __init__(self):
        self.page_size = letter
        self.margin = 0.5 * inch
    
    def generate_mood_report(self, username, mood_history, predictions=None):
        """Generate mood analysis report"""
        try:
            filename = f"{REPORTS_DIR}/mood_report_{username}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
            doc = SimpleDocTemplate(filename, pagesize=self.page_size,
                                  rightMargin=self.margin, leftMargin=self.margin,
                                  topMargin=self.margin, bottomMargin=self.margin)
            
            story = []
            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor=colors.HexColor('#FF6B6B'),
                spaceAfter=30,
            )
            
            # Title
            story.append(Paragraph("🎵 MoodSync - Mood Report", title_style))
            story.append(Spacer(1, 0.2*inch))
            
            # User Info
            story.append(Paragraph(f"<b>Username:</b> {username}", styles['Normal']))
            story.append(Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
            story.append(Spacer(1, 0.3*inch))
            
            # Mood History Summary
            if mood_history:
                story.append(Paragraph("<b>Recent Mood History</b>", styles['Heading2']))
                
                data = [['Timestamp', 'Emotion', 'Confidence']]
                for mood in mood_history[:10]:
                    emotion = mood.get('final_emotion', 'Unknown')
                    conf = mood.get('final_confidence', 0)
                    timestamp = mood.get('timestamp', 'N/A')
                    data.append([str(timestamp)[:10], emotion, f"{conf:.2%}"])
                
                table = Table(data, colWidths=[2*inch, 2*inch, 1.5*inch])
                table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#FF6B6B')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, 0), 14),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                    ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                    ('GRID', (0, 0), (-1, -1), 1, colors.black)
                ]))
                story.append(table)
            
            story.append(Spacer(1, 0.3*inch))
            
            # Predictions
            if predictions:
                story.append(Paragraph("<b>Mood Predictions</b>", styles['Heading2']))
                pred_data = [['Date', 'Predicted Emotion', 'Confidence']]
                for pred in predictions:
                    pred_data.append([
                        pred.get('predicted_date', 'N/A'),
                        pred.get('emotion', 'Unknown'),
                        f"{pred.get('confidence', 0):.2%}"
                    ])
                
                pred_table = Table(pred_data, colWidths=[2*inch, 2*inch, 1.5*inch])
                pred_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4ECDC4')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 1, colors.black)
                ]))
                story.append(pred_table)
            
            story.append(Spacer(1, 0.3*inch))
            story.append(Paragraph("Report generated by MoodSync", styles['Normal']))
            
            doc.build(story)
            logger.info(f"Report generated: {filename}")
            return filename
        except Exception as e:
            logger.error(f"Error generating report: {str(e)}")
            return None
    
    def export_csv(self, username, mood_history):
        """Export mood history to CSV"""
        try:
            import csv
            filename = f"{REPORTS_DIR}/mood_history_{username}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
            
            with open(filename, 'w', newline='') as csvfile:
                fieldnames = ['timestamp', 'face_emotion', 'face_confidence', 'text_emotion', 
                            'text_confidence', 'voice_emotion', 'voice_confidence', 'final_emotion', 'final_confidence']
                writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
                
                writer.writeheader()
                for mood in mood_history:
                    writer.writerow({
                        'timestamp': mood.get('timestamp', ''),
                        'face_emotion': mood.get('face_emotion', ''),
                        'face_confidence': mood.get('face_confidence', ''),
                        'text_emotion': mood.get('text_emotion', ''),
                        'text_confidence': mood.get('text_confidence', ''),
                        'voice_emotion': mood.get('voice_emotion', ''),
                        'voice_confidence': mood.get('voice_confidence', ''),
                        'final_emotion': mood.get('final_emotion', ''),
                        'final_confidence': mood.get('final_confidence', '')
                    })
            
            logger.info(f"CSV exported: {filename}")
            return filename
        except Exception as e:
            logger.error(f"Error exporting CSV: {str(e)}")
            return None
